### ISSUE TITLE
📃: crop disease detection using dl 

### ISSUE THREAD

**Issue by sharath4444** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#105]
🟢 Title :crop disease detection using dl 
🟢 Tech stack :deeplearning algorithms

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :mankala sharathchandra

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by sharath4444** [comment]
please add hacktoberfest label

**Comment by abhisek247767** [comment]
Assigned
