### ISSUE TITLE
want to add classification and regression code using SVM

### ISSUE THREAD

**Issue by shalupatidar22** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#108]
I want to contribute under hacktoberfest2024 please assign me this issue.

**Comment by abhisek247767** [comment]
please check already available. if you want to enhancement then do it.

**Comment by Sohamshah03** [comment]
Is this issue still open. I can contribute. Please assign me this issue.

**Comment by abhisek247767** [comment]
yes. I assigned you also.
