### ISSUE TITLE
📃: image-to-text model

### ISSUE THREAD

**Issue by BhavyaFattania** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#113]
🟢 Title :image captioning model
🟢 Tech stack :python
🟢 Objective :to describe image using text only 
🟢 Summary :this model takes image as input and generates conditional and unconditional captions

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Bhavya Fattania

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by Sohamshah03** [comment]
I can contribute to this issue. Please assign me this issue.

**Comment by abhisek247767** [comment]
Assigned all.
