### ISSUE TITLE
📃: audio-to-text model

### ISSUE THREAD

**Issue by BhavyaFattania** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#114]
🟢 Title :text-to-audio model 
🟢 Tech stack :python
🟢 Objective :to get audio by providing a text
🟢 Summary : this model takes text as input and generates a human like voice output 

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Bhavya Fattania

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by Sohamshah03** [comment]
I can contribute to this issue. Please assign me this issue.

**Comment by abhisek247767** [comment]
Assigned @Sohamshah03
