### ISSUE TITLE
📃: EDA -heart disease

### ISSUE THREAD

**Issue by shailja-07** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#115]
🟢 Title :EDA -heart disease
🟢 Tech stack :python library,jupiter notebook
🟢 Objective :to analyze the heart disease dominant in adults
🟢 Summary :the EDA analyze whether a person has malignant or benign conditions

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Shailja

***********************************************************************

**Comment by abhisek247767** [comment]
Assigned

**Comment by shailja-07** [comment]
i have added my eda ,kindly acknowledge it.
