### ISSUE TITLE
📃: Traffic sign detection using CNN and YOLOv8

### ISSUE THREAD

**Issue by Sohamshah03** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#116]
🟢 Title : Traffic Sign Detection
🟢 Tech stack : Python, Tensorflow
🟢 Objective : To detect various traffic signs like red, green light ,stop sign and various speed limits.
🟢 Summary : To detect various traffic signs in image and video input.

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :  Soham Shah

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by Sohamshah03** [comment]
Please assign me this issue. I can contribute to this issue. Thank you

**Comment by abhisek247767** [comment]
Assigned
