### ISSUE TITLE
📃: Naive Bayes Algorithm from Scratch

### ISSUE THREAD

**Issue by Sohamshah03** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#121]
🟢 Title : Naive Bayes Algorithm from Scratch
🟢 Tech stack : Python
🟢 Objective : To implement and understand Naive Bayes algorithm.
🟢 Summary : Understanding Naive Bayes algorithm

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Soham Shah

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by Sohamshah03** [comment]
Please assign me this issue.

**Comment by abhisek247767** [comment]
Assigned
