### ISSUE TITLE
Repo is hacktoberfest excluded

### ISSUE THREAD

**Issue by Sohamshah03** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#124]
@abhisek247767 please look into it, the repo is hacktoberfest excluded. 
![Screenshot 2024-10-27 153601](https://github.com/user-attachments/assets/f50af7e3-042e-4115-932e-e4f0e044430b)

**Comment by abhisek247767** [comment]
sorry . we are failed to back our repo.
