### ISSUE TITLE
About this repository Customization 

### ISSUE THREAD

**Issue by abhisek247767** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#15]
Please add some necessary customization to the README file, so that other people can contribute to my repository.
Thanks in advance !!

**Comment by Ankitmohanty2** [comment]
Shall i work on this issue??

**Comment by abhisek247767** [comment]
yes sure. Please do. I have also assigned you. also add all contributors in readme.md file

**Comment by Ankitmohanty2** [comment]
thank you
