### ISSUE TITLE
HaarCascade algorithm - Eye blink detection project.

### ISSUE THREAD

**Issue by nycanshu** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#26]
I want to add my project in this repo. Under hacktoberfest2024. 

Project Description :
Eye blink detection and Fatigue alarm.

Algorithm used : HaarCascade Algorithm.

Tech Stack used - Python, CMake, OpenCV for realtime detection.

Please assign me this issue.

**Comment by abhisek247767** [comment]
assigned

**Comment by nycanshu** [comment]
Please assign this to me again. Old request was out of date, so i requested again.

**Comment by abhisek247767** [comment]
Done bro. Please star the repo for future enhancement of the upcoming project.
