### ISSUE TITLE
CNN and RNN Algorithm Implementation using PyTorch

### ISSUE THREAD

**Issue by srirangamuc** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#30]
I'd like to contribute by implementing CNN's and RNN's y explaining and implementing them from scratch. I'd like you to consider this issue under HacktoberFest2024 and Assign me this task

**Comment by abhisek247767** [comment]
Assigned .

**Comment by srirangamuc** [comment]
Respected Sir, I have created a pull request. I'd kindly request you to accept it
