### ISSUE TITLE
XGBoost Algo 

### ISSUE THREAD

**Issue by gigachad80** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#37]
Hey Abhisek!!

In this repo I've introduced XGBoost algo with its characteristics , real life examples , working , advantages . Also I've provided  demo code of XGboost in Python .

**Comment by gigachad80** [comment]
Hey Abhisek!!

In this repo I've introduced XGBoost algo with its characteristics , real life examples , working , advantages . Also I've provided demo code of XGboost in Python .

**Comment by rishabh-108272** [comment]
Hey Abhishek!!

If this issue is not resolved yet. Can I work on this issue?

**Comment by abhisek247767** [comment]
yes please .assigned to you
