### ISSUE TITLE
Yotube Toxic Comments Classification Model

### ISSUE THREAD

**Issue by Blacksujit** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#38]
1.) Enhancing User Experience:
In today's digital world, online communication is widespread, and public platforms like social media, forums, and comment sections allow users to freely express their opinions. However, this often leads to an influx of inappropriate, offensive, or harmful comments

2.) Real-time Moderation:
Manual moderation of comments is time-consuming and often insufficient to handle the massive volume of content generated daily. Machine learning algorithms can be employed to detect and classify toxic comments in real-time

3.) Preventing Online Harassment:
Many people, especially minorities, are often targets of online harassment, which can lead to emotional distress, withdrawal from online communities, or even legal action.

**Comment by abhisek247767** [comment]
Assigned to you !!

**Comment by b423016** [comment]
I can work on this.

**Comment by abhisek247767** [comment]
I assigned it both. please read the guidelines before do the PR. Please star the repo and follow me for my encouragement
