### ISSUE TITLE
Hand-Controlled Screenshot Feature Using OpenCV

### ISSUE THREAD

**Issue by Invincible1602** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#44]
Hey @abhisek247767,

I would like to implement a feature that allows users to take screenshots using hand gestures recognized by OpenCV. This will allow users to control the screenshot functionality without using a keyboard or mouse.

Steps:

* Hand Gesture Recognition: Utilize OpenCV's integration with MediaPipe to detect hand gestures.

* Gesture Mapping: Map specific gestures (e.g., "thumbs up") to trigger the screenshot functionality.

* Screenshot Functionality: Once the gesture is detected, a screenshot of the active window or the screen is taken and saved as an image 
                                            file.

* Customization: Allow the user to customize the gesture used for the screenshot action.

**Comment by abhisek247767** [comment]
start the repo and follow me here for my encouragement
