### ISSUE TITLE
CNN algorithm

### ISSUE THREAD

**Issue by rohitgargRG** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#50]
want to add about CNN algorithm

**Comment by abhisek247767** [comment]
check guidelines @rohitgargRG . star the repo and follow me for my encouragement.

**Comment by rishabh-108272** [comment]
Hey @abhisek247767 

Sorry I'm new to this. How can I raise the new issue with hacktoberfest label?

**Comment by abhisek247767** [comment]
Don't say sorry. It's okay to not know that. 
go to issue tab-> create new issue -> write about issue ->and then create it...you don't need to label it..i will label it hacktoberfest.

let me know if you still don't understand

**Comment by rishabh-108272** [comment]
I understood it. Thanks
