### ISSUE TITLE
Image-Based Emotion Detection

### ISSUE THREAD

**Issue by Apoorva-Datir** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#53]
Hi,
This project would involve detecting human emotions from images using facial recognition and deep learning, followed by generating AI art that reflects the detected mood. This is an interactive project that combines computer vision, machine learning, and generative art.
**Tech stack used** : OpenCV and the FER (Facial Expression Recognition) package.
@abhisek247767  Can you please assign this issue to me under hacktoberfest 2024 ?

**Comment by abhisek247767** [comment]
I assigned it. please read the guidelines before do the PR. Please star the repo and follow me for my encouragement.

**Comment by Apoorva-Datir** [comment]
Hi @abhisek247767 
I have checked the guidelines and made the PR accordingly.
Please review it and merge.
Thanks!
