### ISSUE TITLE
Helmet Detection Model Using OpenCV and CNN

### ISSUE THREAD

**Issue by rishabh-108272** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#54]
Create the helmet detection model using OpenCV, CNN and image segmentation methods to detect the helmets from the traffic in real time.

**Comment by rishabh-108272** [comment]
Can I work on this issue under Hacktoberfest 2024 ?

**Comment by abhisek247767** [comment]
sure

**Comment by rishabh-108272** [comment]
Thanks

**Comment by b423016** [comment]
Please Can I work on this?

**Comment by abhisek247767** [comment]
Please do. I assigned it. please read the guidelines before do the PR. Please star the repo and follow me for my encouragement

**Comment by eeshan15** [comment]
Hey @abhisek247767 I also want to do it please assign it to me as well and also tell do i have to look for dataset from other sources for this ?

**Comment by abhisek247767** [comment]
@eeshan15 Done. Check guidelines properly.

**Comment by eeshan15** [comment]
> @eeshan15 Done. Check guidelines properly.

I guess you are telling me to readme file. But I am asking for dataset please tell me about that Like can I use Kaggle one ?. @abhisek247767

**Comment by abhisek247767** [comment]
yes 

> > @eeshan15 Done. Check guidelines properly.
> 
> I guess you are telling me to readme file. But I am asking for dataset please tell me about that Like can I use Kaggle one ?. @abhisek247767

yes. you can

**Comment by rishabh-108272** [comment]
Why this issue is closed? Is this issue completed?

**Comment by abhisek247767** [comment]
I opened again

**Comment by janviisonii23** [comment]
Hey can you please assign me this issue i think i can work on this.!

**Comment by abhisek247767** [comment]
@janviisonii23 Assigned

**Comment by janviisonii23** [comment]
I am working on helmet detection either by finetuning YOLOv8 or building it from scratch . Both the approaches does not involve image segmentation . So can I go ahead with this approach?

**Comment by abhisek247767** [comment]
@janviisonii23 assigned
