### ISSUE TITLE
Create a guidelines and template for creation of pull request.

### ISSUE THREAD

**Issue by shrek-28** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#57]
1. Define a clear and concise template for creating pull requests to ensure consistency and clarity in the development workflow.
2. Establish guidelines for PR submission, including branch naming conventions, code testing requirements, and documentation updates.
3. Create a checklist to be included in the PR template that covers key review steps (e.g., code formatting, passing tests).
4. Ensure that all contributors are aware of the PR process and have an easy-to-follow template for future contributions.

**Comment by b423016** [comment]
Please assign me this issue

**Comment by abhisek247767** [comment]
okay ...Please do .I have assigned

**Comment by shrek-28** [comment]
your repo has come as excluded under hacktoberfest, please look into it before contributions

**Comment by abhisek247767** [comment]
yes.. some people told me. I already take action on that. i mailed the hacktoberfest community member for where is the issue. They reply there are looking into it and also mentioned primarily in this repo no issue present. may be bot has issue who has identified spammy repository.

**Comment by abhisek247767** [comment]
Now you guys wish
