### ISSUE TITLE
Optimized File Transfer Using Checksums

### ISSUE THREAD

**Issue by pratikj697** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#62]
Problem Statement:
Create a Python script to simulate an optimized file transfer system that compares the checksum of files between two directories and only transfers files that have changed. The goal is to avoid transferring unchanged files to optimize network and disk usage.

Requirements:
1. File Hashing:
Compute the checksum (SHA-256) for each file in the source and destination directories.
2. Transfer Condition:
If a file in the source directory has a different hash than its counterpart in the destination directory (or is missing), it should be transferred.
3. Handling Errors:
Gracefully handle cases where files do not exist in either directory.

Please assign this problem to me under HacktoberFest 2024.

**Comment by abhisek247767** [comment]
I assigned it. please read the guidelines before do the PR. Please star the repo and follow me for my encouragement
