### ISSUE TITLE
Add Logistic Regression Model

### ISSUE THREAD

**Issue by Mefisto04** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#64]
**Description:**
I would like to contribute by adding a Logistic Regression model to the project. Logistic Regression is a powerful and widely used classification algorithm that can be helpful for predicting binary outcomes.

**Proposed Contribution:**
- Implement a Logistic Regression model using Python (or any relevant programming language used in this repository).
- Include a well-documented code that explains each step of the model creation, training, and evaluation process.
- Provide a sample dataset for demonstration and explain how to use the model for predictions.
- Add comments and docstrings for better code readability and understanding.

**Additional Information:**
- Please assign this issue to me so that I can start working on it and contribute to this project.
- Also add tag of Hacktoberfest.

**Comment by abhisek247767** [comment]
I assigned it. please read the guidelines before do the PR. Please star the repo and follow me for my encouragement
