### ISSUE TITLE
Add about "atificial neural network"

### ISSUE THREAD

**Issue by rohitgargRG** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#70]
would like to add details about artificial neural network

**Comment by abhisek247767** [comment]
I assigned it. please read the guidelines before do the PR. Please star the repo and follow me for my encouragement

**Comment by taneeshamadhu18** [comment]
assign me!

**Comment by abhisek247767** [comment]
Done @taneeshamadhu18

**Comment by SparkSidd** [comment]
as i can see no one has raised a pr i can complete it soon please assign this to me

**Comment by abhisek247767** [comment]
Done

**Comment by Salonisaroha** [comment]
please assign me @abhisek247767

**Comment by SparkSidd** [comment]
kindly review it. i have made the pull request

**Comment by abhisek247767** [comment]
@SparkSidd sure

**Comment by SparkSidd** [comment]
can you please merge it

**Comment by abhisek247767** [comment]
can you share the PR @SparkSidd
