### ISSUE TITLE
Implement Naive Bayes Classification Algorithm

### ISSUE THREAD

**Issue by rutubhanderi** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#72]
I would like to propose the addition of the Naive Bayes classification algorithm to this repository. Naive Bayes is a simple yet powerful probabilistic machine learning algorithm commonly used for text classification, spam detection, and other classification tasks. Implementing this algorithm will help contributors understand its practical applications.

**Comment by Sri5275** [comment]
Hi @abhisek247767 , I would like to address this issue can you assign me this issue under hacktoberfest?

**Comment by rutubhanderi** [comment]
@Sri5275 i am creating a issue to open a PR
