### ISSUE TITLE
AI_Health_Predictor

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#75]
An AI model to predict health based on symptoms and suggests medicines, excercise and foods etc...

**Comment by taneeshamadhu18** [comment]
assign me this ! would love to contribute

**Comment by abhisek247767** [comment]
Assigned both

**Comment by taneeshamadhu18** [comment]
Thank you
