### ISSUE TITLE
Loan Approval prediction using Machine Learning

### ISSUE THREAD

**Issue by RajKhanke** [abhisek247767/MachineLearningAlgorithm-Hacktoberfest2022#76]
based on various economical and social factors like loan term , cibil score, loan amount, income etc i will predict whether the loan is approved for the user or not using various machine learning models, a complete analysis and a streamlit based web app for prediction

please assign this issue to me under  hacktoberfest 2024 with label hacktoberfest-accepted

**Comment by abhisek247767** [comment]
Done

**Comment by eeshan15** [comment]
HI i also want to contribute in hacktoberFest2024 I am good at python and a beginner at Open Source can you help? @abhisek247767 @RajKhanke

**Comment by abhisek247767** [comment]
I assigned both. Please do.

**Comment by eeshan15** [comment]
@abhisek247767 bro where is the dataset can you tell?

**Comment by abhisek247767** [comment]
just search on Kaggle you will get many datasets. collect from that. do it.
